name: egilaslak
favicon: null
layout_spectrum: 0.9797643420752138
typography_spectrum: 0.07491056295111775
title: Hjemmesida til Egil Aslak Aursand Hagerup
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4ca2db'
    - '#e1e1e3'
    - '#004484'
    - '#b02f35'
  brandStrength: 0.019472582498565316
  lightness: 0.8001334539148957
  saturation: 0.691779842833057
  rhythmicContrast: 0.9812647614162415
purpose: []
